const trailerMap = {
  'Squid Game':               'oqxAJKy0ii4',
  'Crash Landing on You':     'KTMjTThjsaA',
  'Itaewon Class':            'BoRRgs1EZUQ',
  'My Love from the Star':    'kHMBP0zpbAk',
  'Descendants of the Sun':   'tCCJn1XVFnQ',
  'Goblin':                   'tTPCiHFaKTk',
  'Hospital Playlist':        '9anHaUOZjl0',
  'Reply 1988':               'WKV7Ud4mhBE',
  'Vincenzo':                 'VPD_HFlHWPI',
  'Business Proposal':        'rRjPlTmQaG8',
  'Dirilis Ertugrul':         'x7kEPMuoUMI',
  'Kurulus Osman':            'LTCbZQ5OTXE',
  'Mirzapur':                 'pMBpMGNGCdc',
  'Sacred Games':             'vDMD-DoODPM',
  'Panchayat':                'O0PtJ_1MFkU',
  'Scam 1992':                'JN6Wq-KGPyI',
  'Delhi Crime':              'dSmCODEzMZU',
  'TVF Pitchers':             'wnS7hNFOhCM',
  'Breaking Bad':             'HhesaQXLuRY',
  'Game of Thrones':          'KPLWWIOCOOQ',
  'Money Heist':              'htGc4HaKLxQ',
  'Dark':                     '_IIiFJJJGKE',
  'Stranger Things':          'b9EkMc79ZSU',
  'Parasite':                 '5xH0HfJHsaY',
  'The Dark Knight':          'EXeTwQWrcwY',
  'Inception':                'YoHD9XEInc0',
  'Interstellar':             'zSWdZVtXT7E',
  '3 Idiots':                 'xvszmNXdM4w',
  'Dangal':                   'x_7YlGv9u1g',
  'Avengers Endgame':         'TcMBFSGVi1c',
  'Spider-Man No Way Home':   'JfVOs4VSpmA',
  'The Shawshank Redemption': 'PLl99DlL6b4',
  'Forrest Gump':             'bLvqoHBptjg',
  'Tehran':                   'smMkkOTm1_A',
};

module.exports = { trailerMap };
